/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class frmautenticacao extends javax.swing.JFrame {

    /**
     * Creates new form frmautenticacao
     */
    public frmautenticacao() {
        initComponents();
        setLocationRelativeTo(null);
        progresso1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        progresso1 = new javax.swing.JProgressBar();
        lbl2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JPasswordField();
        txt2 = new javax.swing.JTextField();
        checar1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menu6 = new javax.swing.JMenuBar();
        menu7 = new javax.swing.JMenu();
        item4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Simplex", 0, 36)); // NOI18N
        lbl1.setText("Concessionária");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(progresso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lbl2.setText("Senha:");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, -1));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, -1));

        checar1.setText("Mostrar caracteres");
        checar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checar1ActionPerformed(evt);
            }
        });
        getContentPane().add(checar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 92, -1));

        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 94, -1));

        menu7.setText("Concessionária");

        item4.setText("Sair");
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });
        menu7.add(item4);

        menu6.add(menu7);

        setJMenuBar(menu6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_item4ActionPerformed

    private void checar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checar1ActionPerformed
        String senha = new String(this.txt1.getPassword());
        String senha1 = txt2.getText();
        if (checar1.isSelected()) {
            txt2.setText(senha);
            txt2.setVisible(true);
            txt1.setVisible(false);
        } else {
            txt1.setText(senha1);
            txt2.setVisible(false);
            txt1.setVisible(true);
        }
    }//GEN-LAST:event_checar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String senha = "12345";
        if (txt1.getText().length() > 0 || txt2.getText().length() > 0) {
            if (txt1.getText().equals(senha) || txt2.getText().equals(senha)) {
                new Thread() {
                    public void run() {
                        for (int i = 0; i < 100; i++) {
                            try {
                                txt1.setText("");
                                txt2.setText("");
                                sleep(15);
                                progresso1.setValue(i);
                                if (i <= 25) {
                                    lbl2.setText("Carregando...");
                                }
                                if (i > 25 && i <= 50) {
                                    lbl2.setText("Autenticando...");
                                }
                                if (i > 50 && i <= 100) {
                                    lbl2.setText("Abrindo tela...");
                                }
                            } catch (InterruptedException ex) {
                                JOptionPane.showMessageDialog(null, "Problema ao carregar", "Falha", 0);
                            }
                        }
                        frmmenu menu = new frmmenu();
                        setVisible(false);
                        menu.setResizable(false);
                        menu.setVisible(true);
                    }
                }.start();
            } else {
                JOptionPane.showMessageDialog(null, "Senha inválida", "Erro na autenticação", 1);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos vázios", "Erro na autenticação", 1);
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmautenticacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checar1;
    private javax.swing.JMenuItem item4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JMenuBar menu6;
    private javax.swing.JMenu menu7;
    private javax.swing.JProgressBar progresso1;
    private javax.swing.JPasswordField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}