/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria;

import classes.banco;
import classes.tabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author danie
 */
public class frmchecar extends javax.swing.JFrame {

    banco banco = new banco();

    /**
     * Creates new form frmchecar
     */
    public frmchecar() {
        initComponents();
        setLocationRelativeTo(null);
        banco.conexao();
        preenchertabela("select * from vendafinalizada where cod_venda = '" + this.txt3.getText() + "'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        txt3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JButton();
        btnbuscar2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tabela1);

        txt3.setBackground(java.awt.Color.lightGray);

        jLabel8.setText("CFP DO CLIENTE:");

        btnbuscar1.setBackground(new java.awt.Color(204, 204, 204));
        btnbuscar1.setText("Voltar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        btnbuscar2.setBackground(new java.awt.Color(204, 204, 204));
        btnbuscar2.setText("Checar venda");
        btnbuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Concessionária");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnbuscar2)))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnbuscar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbuscar1)
                .addGap(167, 167, 167))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Object[] opcao = {"Confirmar", "Cancelar"};
        int i = JOptionPane.showOptionDialog(null,
                "Tem certeza que deseja sair?", "Você está prestes a fechar o sistema",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                opcao, opcao[0]);
        if (i == JOptionPane.YES_OPTION) {
            banco.desconecta();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
        frmvenda venda = new frmvenda();
        setVisible(false);
        venda.setResizable(false);
        venda.setVisible(true);
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btnbuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar2ActionPerformed
        // TODO add your handling code here:
        if (txt3.getText().length() > 0) {
            try {
                PreparedStatement pst = banco.con.prepareStatement("select * from vendafinalizada where cpf = '" + this.txt3.getText() + "'");
                banco.rs = pst.executeQuery();
                if (banco.rs.next()) {
                    preenchertabela("select * from vendafinalizada where cpf = '" + this.txt3.getText() + "'");
                } else {
                    JOptionPane.showMessageDialog(null, "CPF não encontrado");
                }
            } catch (SQLException ex) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo 'CPF' vázio");
        }
    }//GEN-LAST:event_btnbuscar2ActionPerformed

    public void preenchertabela(String banco1) {
        //variavel do tipo arratlist
        ArrayList dados = new ArrayList();
        //nomeando as colunas da tabela, usando vetor
        String[] colunas = new String[]{"Código", "CPF", "Valor Total"};
        //comando para buscar dados da tabela
        banco.executaSQL(banco1);
        try {
            //volta para a primeira coluna
            banco.rs.first();
            //pode fazer  com o if
            //realizando busca de dados, caso tenha algum
            //o nome é igual ao nome do campo no bd
            do {
                dados.add(new Object[]{
                    banco.rs.getInt("cod_venda"),
                    banco.rs.getString("cpf"),
                    banco.rs.getDouble("valortotal")});
            } while (banco.rs.next());
        } catch (SQLException ex) {
        }
        tabela table = new tabela(dados, colunas);
        tabela1.setModel(table);
        //preenchendo as tabelas, no caso apenas algumas preferencias
        //no caso defini apenas o tamanho e se ela poderia ser redimensionada
        tabela1.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(0).setResizable(false);
        tabela1.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(1).setResizable(false);
        tabela1.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(2).setResizable(false);
        tabela1.getTableHeader().setReorderingAllowed(false);
        /*opcional*/
        //a tabela não pode ser redimensioanda
        tabela1.setAutoResizeMode(tabela1.AUTO_RESIZE_OFF);
        //seleção única
        tabela1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmchecar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmchecar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmchecar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmchecar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmchecar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnbuscar2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela1;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}