/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria;

import classes.banco;
import classes.conta;
import classes.tabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Daniel
 */
public class frmvenda extends javax.swing.JFrame {

    banco banco = new banco();
    conta c = new conta();

    /**
     * Creates new form frmvenda
     */
    public frmvenda() {
        initComponents();
        //para que a aplicacao abra no centro da tela
        setLocationRelativeTo(null);
        txt4.setEditable(false);
        banco.conexao();
        //já executa o comando para preencher a tabela
        preenchertabela("select * from venda where statusvenda = 'Em andamento'");
        btnadicionar.setEnabled(false);
        painel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        btnnovavenda = new javax.swing.JButton();
        btnbuscar1 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        btnadicionar = new javax.swing.JButton();
        btnbuscar2 = new javax.swing.JButton();
        btnfinalizar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        btnexcluir1 = new javax.swing.JButton();
        btnfinalizar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnnovavenda1 = new javax.swing.JButton();
        btnfinalizar3 = new javax.swing.JButton();
        painel1 = new javax.swing.JPanel();
        txt8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnbuscar3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concessionária - Sistema de vendas");

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tabela1);

        jLabel6.setText("CPF:");

        txt1.setBackground(java.awt.Color.lightGray);
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome:");

        txt2.setBackground(java.awt.Color.lightGray);

        jLabel8.setText("Código da venda:");

        txt3.setBackground(java.awt.Color.lightGray);

        jLabel1.setText("Total da venda:");

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        btnnovavenda.setBackground(new java.awt.Color(204, 204, 204));
        btnnovavenda.setText("Nova venda");
        btnnovavenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovavendaActionPerformed(evt);
            }
        });

        btnbuscar1.setBackground(new java.awt.Color(204, 204, 204));
        btnbuscar1.setText("Buscar CPF");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        txt5.setBackground(java.awt.Color.lightGray);

        jLabel10.setText("Modelo:");

        txt6.setBackground(java.awt.Color.lightGray);

        jLabel11.setText("Valor unitário:");

        txt7.setBackground(java.awt.Color.lightGray);

        btnadicionar.setBackground(new java.awt.Color(204, 204, 204));
        btnadicionar.setText("Adicionar");
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });

        btnbuscar2.setBackground(new java.awt.Color(204, 204, 204));
        btnbuscar2.setText("Buscar");
        btnbuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar2ActionPerformed(evt);
            }
        });

        btnfinalizar.setBackground(new java.awt.Color(204, 204, 204));
        btnfinalizar.setText("Finalizar venda");
        btnfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizarActionPerformed(evt);
            }
        });

        btnvoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        btnexcluir1.setBackground(new java.awt.Color(204, 204, 204));
        btnexcluir1.setText("Excluir venda");
        btnexcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluir1ActionPerformed(evt);
            }
        });

        btnfinalizar1.setBackground(new java.awt.Color(204, 204, 204));
        btnfinalizar1.setText("Atualizar");
        btnfinalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizar1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Placa:");

        btnnovavenda1.setBackground(new java.awt.Color(204, 204, 204));
        btnnovavenda1.setText("Buscar nome");
        btnnovavenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovavenda1ActionPerformed(evt);
            }
        });

        btnfinalizar3.setBackground(new java.awt.Color(204, 204, 204));
        btnfinalizar3.setText("Checar venda");
        btnfinalizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizar3ActionPerformed(evt);
            }
        });

        painel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setText("Placa do veículo:");

        btnbuscar3.setBackground(new java.awt.Color(204, 204, 204));
        btnbuscar3.setText("Remover item");
        btnbuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscar3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenu1.setText("Concessionária");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel1))))
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnnovavenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnnovavenda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnfinalizar3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnfinalizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnadicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnbuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnfinalizar)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnexcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbuscar1)
                            .addComponent(btnnovavenda)
                            .addComponent(btnnovavenda1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnfinalizar1)
                            .addComponent(btnfinalizar3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnbuscar2)
                                .addGap(18, 18, 18)
                                .addComponent(btnadicionar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnfinalizar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnvoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnexcluir1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Object[] opcao = {"Confirmar", "Cancelar"};
        int i = JOptionPane.showOptionDialog(null,
                "Tem certeza que deseja sair?", "Você está prestes a fechar o sistema",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                opcao, opcao[0]);
        if (i == JOptionPane.YES_OPTION) {
            banco.desconecta();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        frmmenu menu = new frmmenu();
        setVisible(false);
        menu.setResizable(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
        if (txt1.getText().length() > 0) {
            try {
                String consulta = "select * from cliente where cpf = '" + this.txt1.getText() + "'";
                PreparedStatement pst = banco.con.prepareStatement(consulta);
                banco.rs = pst.executeQuery(consulta);
                if (banco.rs.next()) {
                    String nome = banco.rs.getString("nome");
                    txt2.setText(nome);
                } else {
                    JOptionPane.showMessageDialog(null, "CPF não encontrado");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao buscar");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campo 'CPF' vázio");
        }
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btnbuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar2ActionPerformed
        // TODO add your handling code here:
        if (txt5.getText().length() > 0) {
            try {
                String consulta = "select * from veiculo where placa = '" + this.txt5.getText() + "'";
                PreparedStatement pst = banco.con.prepareStatement(consulta);
                banco.rs = pst.executeQuery(consulta);
                if (banco.rs.next()) {
                    String modelo = banco.rs.getString("modelo");
                    double valor = banco.rs.getDouble("valor_veiculo");
                    txt6.setText(modelo);
                    txt7.setText("" + valor);
                    btnadicionar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Veículo não encontrado");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao buscar");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campo 'Placa' vázio");
        }
    }//GEN-LAST:event_btnbuscar2ActionPerformed

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        // TODO add your handling code here:
        //se a pessoa clica em adicionar, inicia-se uma venda por isso a string recebe esse valor

        String venda = "Em andamento";
        String venda1 = "Vendido/Reservado";
        if (txt1.getText().length() > 0 && txt2.getText().length() > 0
                && txt3.getText().length() > 0 && txt5.getText().length() > 0
                && txt6.getText().length() > 0 && txt7.getText().length() > 0) {
            try {
                String status = null;
                String consulta = "select * from veiculo where placa = '" + this.txt5.getText() + "'";
                PreparedStatement pst1 = banco.con.prepareStatement(consulta);
                banco.rs = pst1.executeQuery(consulta);
                if (banco.rs.next()) {
                    status = banco.rs.getString("status");
                } else {
                    JOptionPane.showMessageDialog(null, "Veículo não encontrado");
                }
                if (status.equals("Vendido/Reservado")) {
                    JOptionPane.showMessageDialog(null, "Já reservado ou vendido");

                } else {
                    c.valor = Double.parseDouble(txt7.getText());
                    c.adicionar(c.valor);
                    txt4.setText("" + c.saldo);
                    PreparedStatement pst = banco.con.prepareStatement("insert into venda (cod_venda,cpf,nome,placa,modelo,valor_unitario,statusvenda) values (?,?,?,?,?,?,?)");
                    pst.setString(1, txt3.getText());
                    pst.setString(2, txt1.getText());
                    pst.setString(3, txt2.getText());
                    pst.setString(4, txt5.getText());
                    pst.setString(5, txt6.getText());
                    pst.setString(6, txt7.getText());
                    pst.setString(7, venda);
                    pst.executeUpdate();
                    PreparedStatement pst2 = banco.con.prepareStatement("update veiculo set status = ? where placa ='" + this.txt5.getText() + "'");
                    pst2.setString(1, venda1);
                    pst2.executeUpdate();
                    btnadicionar.setEnabled(false);
                    painel1.setVisible(true);
                    preenchertabela("select * from venda where statusvenda = 'Em andamento'");
                }
            } catch (SQLException ex) {
                //se cair no catch, não pode adicionar o valor, por isso fiz isso
                JOptionPane.showMessageDialog(rootPane, "Venda não realizada. Tente mais tarde");
                if (c.saldo < 0) {

                } else {
                    c.remover(c.valor1);
                    txt4.setText("" + c.saldo);
                    txt5.setText("");
                    txt6.setText("");
                    txt7.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos vázios");
        }


    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btnexcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluir1ActionPerformed
        // TODO add your handling code here:
        /*se a venda é excluida automaticamente o status dela passa a ser cancelada
         e o saldo automaticamente é atualizada*/
        String venda = "Cancelada";
        String venda1 = "Dísponivel";
        if (txt5.getText().length() > 0) {
            try {
                if (c.saldo > 0) {
                    c.saldo = 0;
                    txt4.setText("" + c.saldo);
                }
                //só pode executar o cancelamento se a venda estiver com status em andamento
                PreparedStatement pst1 = banco.con.prepareStatement("select * from venda where cod_venda = '" + this.txt3.getText() + "'");
                banco.rs = pst1.executeQuery();
                //se algo for achado, entra no if e ai sim o update é realizado
                if (banco.rs.next()) {

                    PreparedStatement psts = banco.con.prepareStatement("update veiculo set status = ? where placa = '" + txt5.getText() + "'");
                    psts.setString(1, venda1);
                    psts.executeUpdate();
                    PreparedStatement pst = banco.con.prepareStatement("update venda set statusvenda = ? where cod_venda = '" + this.txt3.getText() + "'");
                    pst.setString(1, venda);
                    int resultado = pst.executeUpdate();
                    if (resultado > 0) {
                        btnnovavenda.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Venda não encontrada");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Venda não encontrada ou não realizada");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Cancelamento não realizado. Tente mais tarde");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos vázios/Você precisa inserir a placa referente");
        }
        /*preenchertabela("select * from venda where statusvenda = 'Em andamento'");*/
    }//GEN-LAST:event_btnexcluir1ActionPerformed

    private void btnnovavendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovavendaActionPerformed
        // TODO add your handling code here:
        if (txt1.getText().length() > 0 && txt2.getText().length() > 0) {
            if (txt5.getText().length() > 0 && txt6.getText().length() > 0
                    && txt7.getText().length() > 0) {
                //gerar números aleatórios
                Random gerador = new Random();
                //de 0 até 30000
                txt3.setText("" + gerador.nextInt(30000));
                btnnovavenda.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha o carro");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Busque um cliente e tente novamente");

        }
    }//GEN-LAST:event_btnnovavendaActionPerformed

    private void btnfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizarActionPerformed
        // TODO add your handling code here:
        if (txt3.getText().length() > 0) {
            try {
                String venda = "Concluída";
                String venda1 = "Em andamento";
                String venda2 = "Vendido";
                /*para realizar a compra a venda deve está em andamento, se ela já estiver
                 cancelada, não serve*/
                PreparedStatement pst3 = banco.con.prepareStatement("insert into vendafinalizada (cod_venda,cpf,valortotal) values (?,?,?)");
                pst3.setString(1, txt3.getText());
                pst3.setString(2, txt1.getText());
                pst3.setString(3, txt4.getText());
                PreparedStatement pst = banco.con.prepareStatement("update venda set statusvenda = ? where cod_venda = '" + this.txt3.getText() + "'");
                pst.setString(1, venda);
                PreparedStatement pst2 = banco.con.prepareStatement("select cod_venda from venda where statusvenda = 'Em andamento' and cod_venda = '" + this.txt3.getText() + "'");
                banco.rs = pst2.executeQuery();
                if (banco.rs.next()) {
                    //se a venda estiver em andamento, o update é feito aqui
                    pst.executeUpdate();
                    pst3.executeUpdate();
                    int resul = pst.executeUpdate();
                    //depois de realizado, o carro precisa atualizado
                    if (resul > 0) {
                        JOptionPane.showMessageDialog(null, "Venda finalizada");
                        preenchertabela("select * from venda where statusvenda = 'Em andamento'");
                        txt1.setText("");
                        txt2.setText("");
                        txt3.setText("");
                        txt4.setText("");
                        txt5.setText("");
                        txt6.setText("");
                        txt7.setText("");
                        btnnovavenda.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Venda não localizada");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Venda já cancelada ou não existe");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível realizar a venda. Tente mais tarde");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campos vázios");
        }
    }//GEN-LAST:event_btnfinalizarActionPerformed

    private void btnfinalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizar1ActionPerformed
        // TODO add your handling code here:
        preenchertabela("select * from venda where statusvenda = 'Em andamento'");

    }//GEN-LAST:event_btnfinalizar1ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_txt4ActionPerformed

    private void btnnovavenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovavenda1ActionPerformed
        // TODO add your handling code here:
        if (txt2.getText().length() > 0) {
            try {
                String consulta = "select * from cliente where nome = '" + this.txt2.getText() + "'";
                PreparedStatement pst = banco.con.prepareStatement(consulta);
                banco.rs = pst.executeQuery(consulta);
                if (banco.rs.next()) {
                    String cpf = banco.rs.getString("cpf");
                    txt1.setText(cpf);
                } else {
                    JOptionPane.showMessageDialog(null, "Nome não encontrado");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao buscar");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campo 'Nome' vázio");
        }
    }//GEN-LAST:event_btnnovavenda1ActionPerformed

    private void btnfinalizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizar3ActionPerformed
        // TODO add your handling code here:
        frmchecar frm = new frmchecar();
        setVisible(false);
        frm.setResizable(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnfinalizar3ActionPerformed

    private void btnbuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar3ActionPerformed
        // TODO add your handling code here:
        String venda = "Cancelada";
        String status = "Disponivel";
        if (txt8.getText().length() > 0) {
            try {
                PreparedStatement pst = banco.con.prepareStatement("select * from venda where placa = '" + this.txt8.getText() + "'");
                banco.rs = pst.executeQuery();
                if (banco.rs.next()) {
                    double valor = banco.rs.getDouble("valor_unitario");
                    PreparedStatement pst1 = banco.con.prepareStatement("update venda set statusvenda = ? where placa = '" + this.txt8.getText() + "'");
                    pst1.setString(1, venda);
                    pst1.executeUpdate();
                    PreparedStatement pst2 = banco.con.prepareStatement("update veiculo set status = ? where placa = '" + this.txt8.getText() + "'");
                    pst2.setString(1, status);
                    pst2.executeUpdate();
                    preenchertabela("select * from venda where statusvenda = 'Em andamento'");
                    double valor1 = Double.parseDouble(txt4.getText());
                    double valor2 = valor1 - valor;
                    c.saldo = valor2;
                    txt4.setText(""+valor2);
                } else {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado no carrinho");
                }
            } catch (SQLException ex) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos vazios");
        }
    }//GEN-LAST:event_btnbuscar3ActionPerformed

    public void preenchertabela(String banco1) {
        //variavel do tipo arratlist
        ArrayList dados = new ArrayList();
        //nomeando as colunas da tabela, usando vetor
        String[] colunas = new String[]{"Placa", "Modelo", "Valor", "ID"};
        //comando para buscar dados da tabela
        banco.executaSQL(banco1);
        try {
            //volta para a primeira coluna
            banco.rs.first();
            //pode fazer  com o if
            //realizando busca de dados, caso tenha algum
            //o nome é igual ao nome do campo no bd
            do {
                dados.add(new Object[]{
                    banco.rs.getString("placa"),
                    banco.rs.getString("modelo"),
                    banco.rs.getString("valor_unitario"),
                    banco.rs.getInt("cod_venda")});
            } while (banco.rs.next());
        } catch (SQLException ex) {
        }
        tabela table = new tabela(dados, colunas);
        tabela1.setModel(table);
        //preenchendo as tabelas, no caso apenas algumas preferencias
        //no caso defini apenas o tamanho e se ela poderia ser redimensionada
        tabela1.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(0).setResizable(false);
        tabela1.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(1).setResizable(false);
        tabela1.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(2).setResizable(false);
        tabela1.getColumnModel().getColumn(3).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(3).setResizable(false);
        tabela1.getTableHeader().setReorderingAllowed(false);
        /*opcional*/
        //a tabela não pode ser redimensioanda
        tabela1.setAutoResizeMode(tabela1.AUTO_RESIZE_OFF);
        //seleção única
        tabela1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmvenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmvenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmvenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmvenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmvenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnbuscar2;
    private javax.swing.JButton btnbuscar3;
    private javax.swing.JButton btnexcluir1;
    private javax.swing.JButton btnfinalizar;
    private javax.swing.JButton btnfinalizar1;
    private javax.swing.JButton btnfinalizar3;
    private javax.swing.JButton btnnovavenda;
    private javax.swing.JButton btnnovavenda1;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel1;
    private javax.swing.JTable tabela1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    // End of variables declaration//GEN-END:variables
}